### ISSUE TITLE
rxtx x64 Error

### ISSUE THREAD

**Issue by cefi1846** [SAP/SapMachine#1027]
Stable Library
=========================================
Native lib Version = RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net
Java lib Version   = RXTX-2.1-7
WARNING:  RXTX Version mismatch
	Jar version = RXTX-2.1-7
	native lib Version = RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000180005b00, pid=26984, tid=24688
#
# JRE version: OpenJDK Runtime Environment SapMachine (11.0.13+8) (build 11.0.13+8-LTS-sapmachine)
# Java VM: OpenJDK 64-Bit Server VM SapMachine (11.0.13+8-LTS-sapmachine, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [rxtxSerial.dll+0x5b00]

**Comment by RealCLanger** [comment]
Hi @cefi1846,

you might understand that this problem description is a bit unspecific. Can you please add some more context?

Furthermore, rxtxSerial.dll seems like a 3rd party library. In most of such cases, the issue lies within the 3rd party lib and the VM crashes and reports a crash dump file (hs_err).

Cheers
Christoph

**Comment by RealCLanger** [comment]
Closing this unless there's more info.
