### ISSUE TITLE
JCo initialization failed. Can't load library libsapjco3.dylib

### ISSUE THREAD

**Issue by fere-andrei** [SAP/SapMachine#1237]
Hello!
I have problem at initialisation on my local.
My specs : MacBook Pro (2021) with Apple M1 Max. This problem doesn't  occur on Windows.
I had similar problem for jdk11 wit  build 11.0.16+8-LTS-sapmachine after i switch on  build 11.0.15.0.1+10-LTS the problem was fixed.
Now I have it again for jdk17.  I tried different build versions but the result is the same. The issue is available only with integration pack added.
I will attach the error log.

Thank you!
Andrei Fere
[logerrorjdk17.txt](https://github.com/SAP/SapMachine/files/9403992/logerrorjdk17.txt)
.

**Comment by RealCLanger** [comment]
Hi @fere-andrei,

this looks like an issue with SAP's JCo, not with the JVM (SapMachine in this case). The official way to get support for this is to open a support ticket at SAP for component BC-MID-CON-JCO. However, I'll ping my JCo dev contact for some further advice. They should hopefully contact you soon a post here.

That said, I'm closing this GitHub issue.

Best regards
Christoph

**Comment by sim-lus** [comment]
I'm not totally familiar with Apple, but I think M1 is ARM-based which is currently not supported, see [here](https://launchpad.support.sap.com/#/notes/2786882) and the discussion [here](https://github.com/SAP/SapMachine/issues/810#issuecomment-1027007463)  
For further advise, as mentioned by Christoph, open a support ticket please.

**Comment by fdmeregildo** [comment]
@fere-andrei Have you found a solution for this problem? I have this same situation

**Comment by nicolabeghin** [comment]
@fdmeregildo make sure to download `x64` (and not `aarch64`) SapMachine even if on M1 (Apple Silicon). Then it will work.
![image-20220712-100622](https://user-images.githubusercontent.com/2743637/188618496-65cf341c-a68d-4c21-87dc-38de58fdddb2.png)

This is because JCO is still not available for ARM64/AARCH64 ref. https://support.sap.com/en/product/connectors/jco.html
![image-20220712-100704](https://user-images.githubusercontent.com/2743637/188618678-9fac7bdb-9ac2-4577-bbe8-56613eb7f36f.png)

**Comment by fdmeregildo** [comment]
@nicolabeghin I have installed all the versions for mac and none of them have worked.

**Comment by nicolabeghin** [comment]
@fdmeregildo I'm using 
> openjdk version "17.0.4" 2022-07-19 LTS
> OpenJDK Runtime Environment SapMachine (build 17.0.4+8-LTS-sapmachine)
> OpenJDK 64-Bit Server VM SapMachine (build 17.0.4+8-LTS-sapmachine, mixed mode)

and JCO3 is correctly working. Make sure you set the correct environment variables (`JAVA_HOME` etc) and that this given `x64` version is used and not any other, then it should work!

**Comment by fdmeregildo** [comment]
@nicolabeghin what version of Hybris have you running?

**Comment by fdmeregildo** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/15707963/189799803-2f24dd6c-2981-4e9c-8e25-fa33128e3ff8.png">

**Comment by fdmeregildo** [comment]
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/15707963/189799944-974ade20-8a08-4d48-a177-a34402394059.png">

Hybris Version and Ext Pack
<img width="477" alt="image" src="https://user-images.githubusercontent.com/15707963/189800401-57692e48-4429-448a-840c-43735edf44e3.png">

**Comment by nicolabeghin** [comment]
> @nicolabeghin what version of Hybris have you running?

Running latest `2205_02`

I would check 2 things given the error you're reporting seems more related to not finding libraries and *not* from being unable to load them due to architecture mismatch - in such case you would have something like

> libsapjco3.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)

1. when starting Hybris, it outputs the Java version being used - it could be different than the one shown in terminal after if environment variables are messed up
2. check if you have jco3 libs available in the expected paths, maybe you extracted the Integration Pack incorrectly
3. if you're on a recent OSX, make sure you enable access to files - you should get a popup for fingerprint auth or you can run `sudo spctl --master-disable`
