### ISSUE TITLE
MacOS x64 binaries all report as "damaged" for any recent JDK 20 early access builds

### ISSUE THREAD

**Issue by kjjaeger** [SAP/SapMachine#1283]
I have tried using both the DMG and the tar.gz MacOS x64 binaries and they all report as corrupted.

The exact message is:

“sapmachine-jdk-20.jdk” is damaged and can’t be opened. You should move it to the Trash.

Much older 20ea builds were working fine before.  I was able to run sapmachine-20+15 and earlier without issue.
Starting with sapmachine-20+16 up to sapmachine-20+24, I see the binaries as 'damaged' every time.

Note: I am using MacOS  Monterey version 12.6.1

**Comment by RealCLanger** [comment]
Hi Kenneth,

thanks for reporting this bug. So, you get this error when you e.g. call java -version in the terminal? Or how do you trigger it?

Thanks
Christoph

**Comment by kjjaeger** [comment]
Correct, as well as other commands like javac.

**Comment by RealCLanger** [comment]
I'm starting to wonder whether this has something to do with https://bugs.openjdk.org/browse/JDK-8293550. This change was done in build 16.

**Comment by MBaesken** [comment]
My colleague has an old Mac running on 12.6.1 and tested build 20-ea+25   successfully there.  So the issues you face might have to do with your local setup of macOS.  He hinted that it might have to do with (Settings->Privacy&Security->Developer Tools->Allow Applications that do not meet the System’s security policy) but that is just an idea.

**Comment by MBaesken** [comment]
We checked the same with 20ea build29 on a macOS 13.2  of a colleague and got the same "damaged"  message. This is a very misleading message from macOS (I consider it a bug).  
It seems to come from the fact that the binary is now (since build16) adhoc signed but not notarized.
The downloaded tar.gz file has the extended attribute "com.apple.quarantine"   (this can be shown with xattr  <jdk-tar.gz -file>).  This leads to the message you face.   Instead of setting some central system settings avoiding this "security  feature" ,  xattr -d -r  com.apple.quarantine   <jdk-tar.gz-file>  removes the attribute and the downloaded JDK works nicely.

Introducing notarization on the ea builds will most likely be not possible for us because of the large effort so I think for now this is the way to go. We might look as well into  removing or adjusting the adhoc signing on the ea binaries, maybe this helps too.

**Comment by RealCLanger** [comment]
I have removed the adhoc signing for our ea builds. So it should work as before again from sapmachine20+34 and sapmachine21+8. It would be nice if you could give us some feedback whether it resolves your problem or not. Thanks.
