### ISSUE TITLE
How we can automatically get latest stable version

### ISSUE THREAD

**Issue by mkysoft** [SAP/SapMachine#1286]
I see that SAP Virtual Machine hasn't got repository to get latest stable version easily. Is there any solution for this?

**Comment by RealCLanger** [comment]
Hi,

not sure what exactly you mean. All releases, both GA and EA, can be found in the Releases of this repository. Furthermore, you'll find a neat download section at https://sapmachine.io/. 

With that information I'll close this ticket. But in case this is not sufficient for you, feel free to reopen and let us know what exactly you are looking for.

Best regards
Christoph

**Comment by marchof** [comment]
Ho, [javaalmanc.io](https://javaalmanac.io) author here. Maybe I can clarify the issue a bit. Up to Java 17 there were short links to the latest release, which redirect to the latest release of that major version. For example:

* https://sap.github.io/SapMachine/latest/11
* https://sap.github.io/SapMachine/latest/17

 Since Java 18 these convenient links are not provided any more. So we cannot link to the proper download. Is this on purpose? See:

https://github.com/SAP/SapMachine/tree/gh-pages/latest

**Comment by mkysoft** [comment]
@RealCLanger web ui not enough to install JDK to OS via CLI interface. We need mechanism like apt/yum. Maybe you can exact link to just download latest one.

**Comment by oliver-bendig** [comment]
Hi,
I added direct links to latest releases:
You can append platform and jdk|jre to latest link to get redirected directly to download, e.g.
[https://sap.github.io/SapMachine/latest/17/windows-x64/jdk](https://sap.github.io/SapMachine/latest/17/windows-x64/jdk)

I also fixed latest page for SapMachine 19:
[https://sap.github.io/SapMachine/latest/19](https://sap.github.io/SapMachine/latest/19)

**Comment by marchof** [comment]
@RealCLanger Java 19 looks good now. Is there a reason that there are no links for Java 18? All versions before Java 17 are linked (even if EOL).

**Comment by oliver-bendig** [comment]
> @RealCLanger Java 19 looks good now. Is there a reason that there are no links for Java 18? All versions before Java 17 are linked (even if EOL).
I will have a look at it

**Comment by MBaesken** [comment]
Works for SapMachine21 too, for example  https://sap.github.io/SapMachine/latest/21/macos-x64/jdk/  .
Documented here :  https://github.com/SAP/SapMachine/wiki/Frequently-Asked-Questions#is-there-a-fix-link-to-download-the-latest-stable-version-of-sapmachine
