### ISSUE TITLE
SAP Machine 11 SDK certs are out of date

### ISSUE THREAD

**Issue by VinceVega7** [SAP/SapMachine#1319]
Hi,

Is there a way to update the certs used by SAP Machine 11? OpenJDK Runtime Environment SapMachine (build 11.0.17+8-LTS-sapmachine) or is there an update with newer certs?

Currently when I try to make a https call I receive the following warning:

Caused by: java.security.cert.CertificateExpiredException: NotAfter: Mon Feb 28 17:17:43 EST 2022

**Comment by RealCLanger** [comment]
Hi @VinceVega7,

SapMachine includes the standard root certificates that come with the OpenJDK (see [here](https://github.com/openjdk/jdk/tree/master/src/java.base/share/data/cacerts)). Other vendors, however, include more certificates as far as I know.

Having said that, from your exception message it's hard to deduce which certificate is the culprit here and is expired. Maybe it's some custom certificate? I think we'd need more information to figure it out.

Cheers
Christoph

**Comment by RealCLanger** [comment]
Closing because no further input was received.
