### ISSUE TITLE
 A fatal error has ben detected by the Java Runtime Environment: SIGSEGV (0xb) at pc=0x00007fc7c8b17510, pid=44065, tid=44066

### ISSUE THREAD

**Issue by ICTAGI** [SAP/SapMachine#1364]
Hello,

We are having an issue with our SAP Hana Box, logs as attached. Can anyone assist with a solution.

Regarsd,
John.
[hs_err_pid44065.log](https://github.com/SAP/SapMachine/files/10900407/hs_err_pid44065.log)

**Comment by RealCLanger** [comment]
Hi @ICTAGI,

the hs_err file looks like a crash in Eclipse. If it is in an SAP solution, would you mind opening a support ticket with SAP?

Thanks
Christoph

**Comment by MBaesken** [comment]
looks like this issue :

https://bugs.eclipse.org/bugs/show_bug.cgi?id=572196

also discussed here
https://bugs.eclipse.org/bugs/show_bug.cgi?id=572198
https://www.eclipse.org/forums/index.php/t/1107402/

Seems this has been fixed in higher Eclipse versions.  Most likely we cannot do much much this in the JVM itself.

**Comment by MBaesken** [comment]
here
https://bugs.eclipse.org/bugs/show_bug.cgi?id=572196
also some workarounds are discussed, in case using a higher version is not possible, hope that helps.
