### ISSUE TITLE
Stale releases `sapmachine-17`, `sapmachine-21`

### ISSUE THREAD

**Issue by mpern** [SAP/SapMachine#1641]
The github releases `sapmachine-17` and `sapmachine-21` point to now outdated patch releases.

- [sapmachine-17](https://github.com/SAP/SapMachine/releases/tag/sapmachine-17) vs [sapmachine-17.0.10](https://github.com/SAP/SapMachine/releases/tag/sapmachine-17.0.10)
- [sapmachine-21](https://github.com/SAP/SapMachine/releases/tag/sapmachine-21) vs [apmachine-21.0.2](https://github.com/SAP/SapMachine/releases/tag/sapmachine-21.0.2)

This breaks downstream tooling like [asdf-vm](https://asdf-vm.com/), [mise](https://mise.jdx.dev/) and others because the use the GH release information to determine the available versions.

The easiest fix would be to get rid of all GH releases with a truncated versions (add `.0.0` as minor and patch version) and make sure that the initial release is always `XX.0.0`

**Comment by RealCLanger** [comment]
Hi @mpern,

we can not delete the outdated releases from GitHub. We never do, since we can not know which automation relies on them. One could say it is unfortunate that the OpenJDK delivers the initial release of a major without .0* and then only adds it to update versions, but that's how it is and has been for quite a while now.
If that's a problem for tooling, one should have a look at the tools, I guess.

Not sure whether the tools could also use our release information data, e.g. https://sap.github.io/SapMachine/assets/data/sapmachine-releases-latest.json

Or the "latest version" links like https://sap.github.io/SapMachine/latest/17 ?

**Comment by mpern** [comment]
HI @RealCLanger,

thanks for the reply!
I wasn't aware that the versioning scheme is coming from OpenJDK, the more you know...

thanks for the links, this gives me some ideas for a PR for the downstream tooling. Looks like we need to sneak in a `.0.0` somewhere...
