### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by Cyclenerd** [SAP/SapMachine#310]
Hi,

I was at the FOSDEM talk from @simonis. This is how I become aware of the SapMachine project

Now to my request: A Windows Installer for SapMachine would be great. That's why I built one. Please have a look: https://github.com/Cyclenerd/SapMachineInstaller

With an installer a roll-out in companies is much easier and in general everything would be much easier.

Do you see a chance to implement the installer in your build process so that there is always an installer version for Windows besides the ZIP?

Best regards
Nils

**Comment by simonis** [comment]
Hi Nils,

thanks a lot for your interest in SapMachine and for your SapMachineInstaller. It looks impressive and I agree that it can simplify the installation of SapMachine considerably.

Unfortunately, we still don't have our "Contributor Agreement" in place (but we're working hard to getting it done).

I'm also not familiar with NSIS but it seems to consume quite some other open source libraries, so we would need to do a license check before we can use it.

But the idea of having a Windows installer is definitely attractive. So please bear with us, until we've sorted out the above mentioned points.

**Comment by Cyclenerd** [comment]
Hi Volker,

many thanks for the quick feedback.

My code is published under the GNU Public License version 2. All NSIS source code, plug-ins, examples, header files, graphics and the zlib compression module are licensed under the zlib/libpng license.
According to Wikipedia the zlib license has been approved by the FSF as a free software license, and by the OSI as an open source license. It is compatible with the GNU General Public License.

I've previously signed a CLA from SAP. Back then via cla-assistant.io. Seems to be already activated for this project: https://cla-assistant.io/SAP/SapMachine

Best regards
Nils

**Comment by simonis** [comment]
Hi Nils,

good to know that you've signed the SAP CLA. Because we are a downstream project of OpenJDK, we try to bring as many as possible of our changes into the upstream OpenJDK project. But the OpenJDK project has its own Contribution Agreement (called OCL for "[Oracle Contribution Agreement](https://www.oracle.com/technetwork/oca-405177.pdf)").

So we actually want to make sure that for every contribution to SapMachine we have the right to contribute them up-stream to the OpenJDK ourselves under the OCA. From my understanding, the SAP CLA is already "strong" enough to give SAP the right to contribute all changes it receives under the SAP CLA to other projects under their CLA. But this question is still under internal, legal review.

Regards,
Volker

**Comment by reshnm** [comment]
Windows installers are now created with every SapMachine release and are provided at sapmachine.io
For example: https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.2/sapmachine-jdk-11.0.2_windows-x64_bin.msi
