### ISSUE TITLE
Add Amazon Root CAs to SapMachine 

### ISSUE THREAD

**Issue by JCA1988** [SAP/SapMachine#482]
Please add the Amazon Root CAs: https://www.amazontrust.com/repository/ to the CAcert in SapMachine. These are required for our product integrating with AWS. Thanks

**Comment by MSailer** [comment]
Hi @JCA1988,

thanks for filing this issue, I will look into it and get back to you soon!

**Comment by RealCLanger** [comment]
Hi @JCA1988,

I just like to update this ticket and let you know that we're still working on this issue.

As you can imageine, it's not too trivial to get all the legal information and approvals for fulfiling such a request. Please bear with us for another while.

Best regards
Christoph

**Comment by RealCLanger** [comment]
Hi,

we've got confirmation that the Amazon Root CAs will be added to OpenJDK in the very near future. Oracle and Amazon did all their legal prerequisites and adding the certificates will be tracked with Open JDK bug https://bugs.openjdk.java.net/browse/JDK-8233223.
This should be commited to jdk mainline very soon and will be backported to other JDK updates immediately. Because of that I'm closing this issue.

Thanks
Christoph
