### ISSUE TITLE
libjpeg 6b vulnerabilities

### ISSUE THREAD

**Issue by anbrsap** [SAP/SapMachine#693]
SapMachine/OpenJDK includes [IJG](https://www.ijg.org/)'s libjpeg version 6b (`src/java.desktop/share/native/libjavajpeg` -> `lib/libjavajpeg.so`, `lib/libsplashscreen.so`). This version of libjpeg has some known vulnerabilities:

- [CVE-2020-14151](https://nvd.nist.gov/vuln/detail/CVE-2020-14151)/[CVE-2018-11813](https://nvd.nist.gov/vuln/detail/CVE-2018-11813) (may not apply to OpenJDK as source file `tdtarga.c` is not included)
- [CVE-2020-14152](https://nvd.nist.gov/vuln/detail/CVE-2020-14152)
- [CVE-2020-14153](https://nvd.nist.gov/vuln/detail/CVE-2020-14153)

Vendor recommendation is to upgrade to version 9d.

Please check whether SapMachine/OpenJDK inherits the above-mentioned vulnerabilities!

**Comment by ArnoZeller** [comment]
Hi Andreas,

I am not sure who created these CVEs but it were not the libjpeg maintainers :-). We already had a look at these issues. 

-  **CVE-2020-14151** -> duplicate of **CVE-2018-11813**.
This CVE is not relevant. As you already mentioned above - the code in question is not included in SapMachine/OpenJDK and as far as I can see the issue was not even in libjpeg 6b.
- **CVE-2020-14153**
The issue only affects libjpeg versions 8 up to 9c, since the variable lim_Se entry was not present in versions before 8 – the creator of the CVE simply missed this part of the issue. Therefore the "Known Affected Software Configurations" sections is wrong and should be fixed. Not sure who can do this.
- **CVE-2020-14152**
For this one I cannot estimate the impact on SapMachine/OpenJDK. But it would be easy to include the proposed fix. You should probably start a discussion on an OpenJDK mailing list to get a better understanding if this mitigation is helpful in the context of OpenJDK.

Best regards,
Arno

**Comment by anbrsap** [comment]
@ArnoZeller Thanks for the detailed reply.

Regarding CVE-2020-14152 I've contacted vuln-report@openjdk.java.net.
