### ISSUE TITLE
Issue while logging into on-premise HANA 2 Database

### ISSUE THREAD

**Issue by MKR1234** [SAP/SapMachine#705]
Dear SAP,

I have an issue that works fine with the Oracle Java 8 version but does not work on any openJDK Java including SapMachine. 
While logging into the Database using Eclipse SAP HANA Administration Console there comes a java Error:
 java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException

Could you please take a look into it. 
KR
Markus

**Comment by RealCLanger** [comment]
Hi Markus,,

this probably doesn't work on any JDK11 or later due to this: http://openjdk.java.net/jeps/320

Module java.xml.ws (which used to contain javax/xml/soap/**) was removed.

So whether and when SAP Hana Administration Console will support a JDK >= 11 is a question for SAP HANA.

Best regards
Christoph

**Comment by MKR1234** [comment]
Hallo Christoph.

Vielen Dank für die schnelle Antwort.
Ich hatte bereits eine Menge recherchiert aber nie genau gefunden warum der Fehler auftritt.
Ich stehe da technisch auch nicht so weit in der Thematik.

Vielleicht ist das nochmal einen zusätzliche Hinweis auf Eurer Seite oder den SAP Dev Tools wert.

Viele Grüße
Markus


Best regards

Markus Kraetzschmar
SAP Development
IT Governance – IT Change Management

Phone: +49 2102 123 45206
markus.kraetzschmar@esprit.com<mailto:markus.kraetzschmar@esprit.com>
