### ISSUE TITLE
Is it possible to get a SAP Machine 11/15 that runs on Alpine Linux x86_64?

### ISSUE THREAD

**Issue by agu3rra-sap** [SAP/SapMachine#796]
Hello colleagues,

I am trying to run SAP Machine's Java (both 11 and 15) on an Alpine based container and it appears that there's an issue related to the fact that Alpine uses a different Standard C library than most other Linux distros ([musl-libc intead of glibc](https://serverfault.com/questions/960772/installing-openjdk-11-on-alpine3-9)). The work around provided in the link does work now that there's an APK Add package for OpenJDK11, but my preference would be to use SAP Machine (specially to relief any licensing investigation burden). Can you make one available?

When downloading either SAP Machine 11 or 15 and running the `./java -version` I get an error message stating *"No such file or directory"* with an exit code 127.

Thank you.

**Comment by RealCLanger** [comment]
Hi Andre,

yes, alpine is a bit different in that it uses musl-libc instead of glibc. For SapMachine, we started to do builds for alpine some time ago but since we could not identify a stakeholder within SAP that would eventually consume this, we stopped our efforts again. Nevertheless, we would reconsider Alpine builds again, in case you have a valid business case. I suggest you reach out to us via direct channels (e.g. sapmachine@sap.com) to discuss this further.

With that I'm closing this issue - please get in touch :)

Cheers
Christoph
